[build.environment]
  # bypass npm auto install
  NPM_FLAGS = "--version"
  NODE_VERSION = "22"

[build.processing]
  skip_processing = true

[build]
  publish = "dist"
  command = "pnpm run build"

# Netlify Image CDN support
[[redirects]]
  from = "/cdnimg/:path"
  to = "/.netlify/images?url=/media/:path"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
