// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/about/About.vue')['default']
    BackBackground: typeof import('./components/gallery/cardBack/BackBackground.vue')['default']
    BackCard: typeof import('./components/gallery/cardBack/BackCard.vue')['default']
    BackCategory: typeof import('./components/gallery/cardBack/absolutes/BackCategory.vue')['default']
    BackCloseButton: typeof import('./components/gallery/cardBack/absolutes/BackCloseButton.vue')['default']
    BackDesc: typeof import('./components/gallery/cardBack/BackDesc.vue')['default']
    BackEmbed: typeof import('./components/gallery/cardBack/BackEmbed.vue')['default']
    Background: typeof import('./components/Background.vue')['default']
    BackLinks: typeof import('./components/gallery/cardBack/BackLinks.vue')['default']
    BackLogo: typeof import('./components/gallery/cardBack/absolutes/BackLogo.vue')['default']
    BackTitle: typeof import('./components/gallery/cardBack/BackTitle.vue')['default']
    BackTitledDesc: typeof import('./components/gallery/cardBack/BackTitledDesc.vue')['default']
    DarkBackground: typeof import('./components/gallery/cardBack/DarkBackground.vue')['default']
    DarkTheme: typeof import('./components/header/DarkTheme.vue')['default']
    DarkThemeIcon: typeof import('./components/footer/icons/DarkThemeIcon.vue')['default']
    EmailIcon: typeof import('./components/footer/icons/EmailIcon.vue')['default']
    ExpandableContent: typeof import('./components/about/ExpandableContent.vue')['default']
    Footer: typeof import('./components/footer/Footer.vue')['default']
    FooterIcon: typeof import('./components/footer/FooterIcon.vue')['default']
    FooterIcons: typeof import('./components/footer/FooterIcons.vue')['default']
    FrontCard: typeof import('./components/gallery/cardFront/FrontCard.vue')['default']
    FrontLogo: typeof import('./components/gallery/cardFront/FrontLogo.vue')['default']
    FrontTitle: typeof import('./components/gallery/cardFront/FrontTitle.vue')['default']
    FrontYear: typeof import('./components/gallery/cardFront/FrontYear.vue')['default']
    Gallery: typeof import('./components/gallery/Gallery.vue')['default']
    GalleryBar: typeof import('./components/gallery/GalleryBar.vue')['default']
    GalleryBarBadge: typeof import('./components/gallery/GalleryBarBadge.vue')['default']
    GalleryBarBadges: typeof import('./components/gallery/GalleryBarBadges.vue')['default']
    GalleryBarSearch: typeof import('./components/gallery/GalleryBarSearch.vue')['default']
    GalleryCard: typeof import('./components/gallery/GalleryCard.vue')['default']
    GalleryCardBack: typeof import('./components/gallery/cardBack/GalleryCardBack.vue')['default']
    GalleryCardFront: typeof import('./components/gallery/cardFront/GalleryCardFront.vue')['default']
    GalleryGrid: typeof import('./components/gallery/GalleryGrid.vue')['default']
    GitHubIcon: typeof import('./components/footer/icons/GitHubIcon.vue')['default']
    Header: typeof import('./components/header/Header.vue')['default']
    ProfileImage: typeof import('./components/header/ProfileImage.vue')['default']
    ScrollButton: typeof import('./components/scrolling/ScrollButton.vue')['default']
    ScrollDown: typeof import('./components/scrolling/ScrollDown.vue')['default']
    ScrollToEdge: typeof import('./components/scrolling/ScrollToEdge.vue')['default']
    Title: typeof import('./components/header/Title.vue')['default']
    ToggleableFieldset: typeof import('./components/about/ToggleableFieldset.vue')['default']
    YoutubeIcon: typeof import('./components/footer/icons/YoutubeIcon.vue')['default']
  }
}
