// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackBackground: typeof import('./components/gallery/cardBack/BackBackground.vue')['default']
    BackCard: typeof import('./components/gallery/cardBack/BackCard.vue')['default']
    BackCategory: typeof import('./components/gallery/cardBack/BackCategory.vue')['default']
    BackDesc: typeof import('./components/gallery/cardBack/BackDesc.vue')['default']
    Background: typeof import('./components/Background.vue')['default']
    BackLogo: typeof import('./components/gallery/cardBack/BackLogo.vue')['default']
    BackTitle: typeof import('./components/gallery/cardBack/BackTitle.vue')['default']
    CardBackBackground: typeof import('./components/gallery/cardBack/CardBackBackground.vue')['default']
    CardBackCard: typeof import('./components/gallery/cardBack/CardBackCard.vue')['default']
    CardBackCategory: typeof import('./components/gallery/cardBack/CardBackCategory.vue')['default']
    CardBackDesc: typeof import('./components/gallery/cardBack/CardBackDesc.vue')['default']
    CardBackLogo: typeof import('./components/gallery/cardBack/CardBackLogo.vue')['default']
    CardBackTitle: typeof import('./components/gallery/cardBack/CardBackTitle.vue')['default']
    copy: typeof import('./components/gallery/cardBack/CardBackTitle copy.vue')['default']
    DarkThemeIcon: typeof import('./components/footer/icons/DarkThemeIcon.vue')['default']
    Footer: typeof import('./components/footer/Footer.vue')['default']
    FooterIcon: typeof import('./components/footer/FooterIcon.vue')['default']
    FooterIcons: typeof import('./components/footer/FooterIcons.vue')['default']
    FrontCard: typeof import('./components/gallery/cardFront/FrontCard.vue')['default']
    FrontLogo: typeof import('./components/gallery/cardFront/FrontLogo.vue')['default']
    FrontTitle: typeof import('./components/gallery/cardFront/FrontTitle.vue')['default']
    Gallery: typeof import('./components/gallery/Gallery.vue')['default']
    GalleryCard: typeof import('./components/gallery/GalleryCard.vue')['default']
    GalleryCardBack: typeof import('./components/gallery/cardBack/GalleryCardBack.vue')['default']
    GalleryCardFront: typeof import('./components/gallery/cardFront/GalleryCardFront.vue')['default']
    GalleryFilter: typeof import('./components/gallery/GalleryFilter.vue')['default']
    GalleryFilterBadge: typeof import('./components/gallery/GalleryFilterBadge.vue')['default']
    GalleryFilterSearch: typeof import('./components/gallery/GalleryFilterSearch.vue')['default']
    GalleryGrid: typeof import('./components/gallery/GalleryGrid.vue')['default']
    GallerySearch: typeof import('./components/gallery/GallerySearch.vue')['default']
    GitHubIcon: typeof import('./components/footer/icons/GitHubIcon.vue')['default']
    HelloThere: typeof import('./components/HelloThere.vue')['default']
    StarsBackground: typeof import('./components/StarsBackground.vue')['default']
    YoutubeIcon: typeof import('./components/footer/icons/YoutubeIcon.vue')['default']
  }
}
